services:
  api_app:
    build:
      context: ./fast-api
    container_name: api_app
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared_logs:/shared/logs
    networks:
      - app_network

networks:
  app_network:
    external: true
    name: dataflow_network