services:
  kafka:
    image: bashj79/kafka-kraft:latest
    container_name: kafka
    restart: always
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:${KAFKA_INTERNAL_PORT},CONTROLLER://0.0.0.0:${KAFKA_CONTROLLER_PORT}"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${KAFKA_ADVERTISED_HOST}:${KAFKA_INTERNAL_PORT}"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "${KAFKA_AUTO_CREATE_TOPICS_ENABLE}"
      KAFKA_MESSAGE_MAX_BYTES: 200000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 200000000
      KAFKA_DATA_DIR: /bitnami/kafka/data
    volumes:
      - kafka_data:/bitnami/kafka/data
    networks:
      - app_network


  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - kafka
    networks:
      - app_network


  init-topics:
    build:
      context: .
      dockerfile: ./services/init-topic/Dockerfile
    networks:
      - app_network

networks:
  app_network:
    external: true
    name: dataflow_network

volumes:
  kafka_data: