services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app_network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    restart: always
    networks:
      - app_network
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/data

networks:
  app_network:
    external: true
    name: dataflow_network

volumes:
  redisinsight_data: