services:
  api_app:
    build:
      context: ./fast-api
    container_name: api_app
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app_network

networks:
  app_network:
    name: dataflow_network