services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "${POSTGRES_PORTS}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: main
    volumes:
      - ./pgdata:/var/lib/postgresql
      - ./shared_logs:/shared/logs
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_panel
    restart: always
    ports:
      - "${PGADMIN_PORTS}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./scripts:/scripts
    networks:
      - app_network
    entrypoint: ["sh", "-c", "/scripts/wait-for-it.sh db:5432 -- /entrypoint.sh"]

volumes:
  pgadmin-data:

networks:
  app_network:
    external: true
    name: dataflow_network