services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9100:9010"
      - "9101:9011"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --address ":9010" --console-address ":9011"
    volumes:
      - ./minio-data:/data
      - ./shared_logs:/shared/logs
    restart: always
    networks:
      - project_default

networks:
  project_default:
    name: dataflow_network
